apiVersion: apps/v1
kind: Deployment
metadata:
  name: scadalts
  labels:
    app: scadalts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scadalts
  template:
    metadata:
      labels:
        app: scadalts
    spec:
      volumes:
        - name: htb-st
      containers:
        - name: mysql
          iamge: mysql/mysql-server:5.7
          ports: 
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: scadalts
        - name: scadalts
          image: scadalts/scadalts:latest
          ports:
            - containerPort: 8000
            - containerPort: 8080

